// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ControllerReviewController from "./controller_review_controller"
application.register("controller-review", ControllerReviewController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MarkAsReadController from "./mark_as_read_controller"
application.register("mark-as-read", MarkAsReadController)
